[custom]
;不要随意改变关键字，否则会导致出错
;自用规则

;规则集定义
ruleset=🇯🇵 日本线路,https://raw.githubusercontent.com/ashakii/zyashakii/refs/heads/main/Japan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ashakii/zyashakii/refs/heads/main/Direct.list
ruleset=🚀 自用网站,https://raw.githubusercontent.com/ashakii/zyashakii/refs/heads/main/ZiYong.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ashakii/zyashakii/refs/heads/main/AI.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ashakii/zyashakii/refs/heads/main/BanAD.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=🚀 节点选择`select`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🚀 自用网站`select`[]🚀 节点选择`[]🔯 日本故转`[]🇺🇲 美国节点`[]🔯 香港故转`[]🇭🇰 香港节点`[]🐸 手动切换
custom_proxy_group=🇯🇵 日本线路`select`[]🚀 节点选择`[]🔯 日本故转`[]🇯🇵 日本节点`[]🐸 手动切换
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🐸 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🐸 手动切换`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]♻️ 自动选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🐸 手动切换`select`.*

custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|港|HK|Hong Kong|🇭🇰|HongKong))^((?!(家宽)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽)).)*$
custom_proxy_group=🇸🇬 加坡节点`select`(?=.*(新加坡|台|韩|坡|狮城|SG|Singapore))^((?!(家宽)).)*$
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🔯 香港故转`fallback`(?=.*(香港|港|HK|Hong Kong|🇭🇰|HongKong))^((?!(家宽)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 日本故转`fallback`(?=.*(日本|日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 加坡故转`fallback`(?=.*(新加坡|坡|台|韩|狮城|SG|Singapore))^((?!(家宽)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 美国故转`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(游戏)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50


enable_rule_generator=true
overwrite_original_rules=true
